<?php
/**
 * Implementation of hook_menu()
 */
function custom_active_menu_menu() {
  $items['admin/config/user-interface/custom-active-menu'] = array(
    'title' => t('Custom Active Menu'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('custom_active_menu_settings_form'),
    'access arguments' => array('administer custom_active_menu'),
  );
  return $items;
}

/*
 * Implementation of hook_permission()
 */
function custom_active_menu_permission() {
  return array(
    'administer custom_active_menu' => array(
      'title' => t('Administer Custom Active Menu'),
      'description' => t('Allows to users edit the menu item to indicate when is active.'),
    ),
  );
}

/*
 * Settings form configuration
 */
function custom_active_menu_settings_form($form_state) {
  $form = array();
  $form['custom_active_menu_li_classes'] = array(
    '#type' => 'textfield',
    '#title' => t('List classes'),
    '#description' => t('Classes applied to <strong>li</strong> element (separate classes with spaces)'),
    '#default_value' => variable_get('custom_active_menu_li_classes', ''),
  );
  $form['custom_active_menu_a_classes'] = array(
    '#type' => 'textfield',
    '#title' => t('Link classes'),
    '#description' => t('Classes applied to <strong>a</strong> element (separate classes with spaces)'),
    '#default_value' => variable_get('custom_active_menu_a_classes', ''),
  );
  return system_settings_form($form);
}

/*
 * Implementation of hook_menu_edit_item_alter()
 */
function custom_active_menu_form_menu_edit_item_alter(&$form, &$form_state) {
  if (user_access('administer custom_active_menu')) {
    $form['options'] = array(
      '#tree' => TRUE,
      '#weight' => 50,
    );
    $form['options']['custom_active_menu'] = array(
      '#type' => 'fieldset',
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#title' => t('Custom Active Menu'),
      '#weight' => 0,
    );
    $form['options']['custom_active_menu']['pages'] = array(
      '#type' => 'textarea',
      '#title' => t('Pages'),
      '#description' => t('Pages where the menu will be active, Enter one page per line as Drupal paths. The \'*\' character is a wildcard. Example paths are blog for the blog page and blog/* for every personal blog.'),
      '#default_value' => isset($form['original_item']['#value']['options']['custom_active_menu']['pages']) ? $form['original_item']['#value']['options']['custom_active_menu']['pages'] : '',
    );
  }
}
/**
 * Implementation of hook_preprocess_menu_link().
 */
function custom_active_menu_preprocess_menu_link(&$variables) {
  if (isset($variables['element']['#localized_options']['custom_active_menu']['pages'])) {
    $pages = $variables['element']['#localized_options']['custom_active_menu']['pages'];
    $path = drupal_get_path_alias($_GET['q']);
    // Compare with the internal and path alias (if any).
    $page_match = drupal_match_path($path, $pages);
    if ($path != $_GET['q']) {
      $page_match = $page_match || drupal_match_path($_GET['q'], $pages);
    }
  }
  if (isset($page_match) && $page_match) {
    $variables['element']['#attributes']['class'][] = variable_get('custom_active_menu_li_classes', 'active-trail');
    $variables['element']['#localized_options']['attributes']['class'][] = variable_get('custom_active_menu_a_classes', 'active');
  }
}